import json
from pathlib import Path
from typing import List #, Dict
from .llm_client import LLMClient
from .config import get_config

class Reviewer:

    def __init__(self):
        self.client = LLMClient()
        self.config = get_config()

    def _parse_notebook(self, file_path: Path) -> str:
        """
        Parses a Jupyter Notebook file and extracts code and markdown cells,
        ignoring outputs to save space.
        """
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                notebook = json.load(f)
            
            content = []
            for cell in notebook.get('cells', []):
                cell_type = cell.get('cell_type', '')
                source = cell.get('source', [])
                if isinstance(source, list):
                    source = "".join(source)
                
                if cell_type == 'code':
                    content.append(f"```python\n{source}\n```")
                elif cell_type == 'markdown':
                    content.append(f"{source}")
            
            return "\n\n".join(content)
        except Exception as e:
            return f"Error parsing notebook: {e}"

    def review_submission(self, directory: Path, stdout: str, stderr: str, solution_path: str = None) -> str:
        """
        Generates a review for a single submission using a multi-step process.
        1. Generate a review plan (select files).
        2. Analyze requirement fulfillment.
        3. Verify execution results against requirements.
        """
        # Exclude files generated by the tool
        generated_files = {"run_submission.sh", "execution_agent.log", "reviewer_agent.log", "review.md"}
        
        # Get all student files (exclude generated files and markdown)
        all_files = [
            f for f in directory.iterdir() 
            if f.is_file() and f.name not in generated_files and not f.name.endswith(".md")
        ]
        
        # If there's both a .ipynb and .py with the same base name, exclude the .py (it was generated)
        notebook_bases = {f.stem for f in all_files if f.name.endswith(".ipynb")}
        all_files = [
            f for f in all_files 
            if not (f.name.endswith(".py") and f.stem in notebook_bases)
        ]
        
        file_list_str = "\n".join([f.name for f in all_files])

        # Initialize log
        log_path = directory / "reviewer_agent.log"
        with open(log_path, "w") as log_file:
            log_file.write(f"--- Reviewing Submission in: {directory} ---\n")
            log_file.write(f"Files found: {[f.name for f in all_files]}\n\n")

        # Load Assignment Description
        assignment_desc = ""
        desc_path = directory.parent / "assignment_description.md"
        if desc_path.exists():
             assignment_desc = desc_path.read_text(errors='replace')

        # Load Instructor Solution
        solution_content = ""
        if solution_path:
             sol_p = Path(solution_path)
             if sol_p.exists():
                 if sol_p.name.endswith(".ipynb"):
                     solution_content = self._parse_notebook(sol_p)
                 else:
                     solution_content = sol_p.read_text(errors='replace')

        # Step 1: Generate Review Plan
        plan_prompt = f"""
You are an expert Computer Science instructor. You need to review a student's submission.
The submission contains the following files:
{file_list_str}

Which of these files are source code or configuration files that are critical for understanding the student's implementation?
Ignore data files (csv, json, txt), images, compiled binaries, or system files unless they seem critical.
If a Jupyter notebook (.ipynb) is present, prefer reviewing it over .py files.

Return ONLY a list of filenames to review, one per line. Do not include any other text.
"""
        with open(log_path, "a") as log_file:
            log_file.write("--- Step 1: Review Plan Prompt ---\n")
            log_file.write(plan_prompt + "\n\n")

        try:
            plan_response = self.client.generate_text(
                prompt=plan_prompt,
                model=self.config.reviewer_model,
                provider=self.config.reviewer_provider,
                system_prompt="You are a helpful teaching assistant."
            )
            
            with open(log_path, "a") as log_file:
                log_file.write("--- Step 1: Review Plan Response ---\n")
                log_file.write(plan_response + "\n\n")

            # Parse the plan
            files_to_review = [line.strip() for line in plan_response.splitlines() if line.strip()]

            # Filter valid files
            selected_files = [f for f in all_files if f.name in files_to_review]

            # Fallback if model returns nothing or garbage
            if not selected_files:
                print(f"Warning: Review plan returned no valid files. Falling back to all files. Plan: {plan_response}")
                selected_files = all_files

        except Exception as e:
            print(f"Error generating review plan: {e}. Falling back to all files.")
            selected_files = all_files

        code_content = ""

        # We still need some limit to avoid hard API errors, but we can be generous if we split.
        # 200k tokens is roughly 800k characters.
        # Let's set a safety limit of 500k chars for code.
        max_total_code_len = 500000 
        total_code_len = 0

        for f in selected_files:

            # Skip very large files (likely data or binaries), but allow notebooks to be parsed
            if f.stat().st_size > 100000 and not f.name.endswith(".ipynb"):
                code_content += f"\n--- File: {f.name} (Skipped - Too Large > 100KB) ---\n"
                continue

            try:
                if f.name.endswith(".ipynb"):
                    content = self._parse_notebook(f)
                else:
                    content = f.read_text(errors='replace')

                if total_code_len + len(content) > max_total_code_len:
                    code_content += f"\n--- File: {f.name} (Skipped - Total Limit Reached) ---\n"
                    continue

                code_content += f"\n--- File: {f.name} ---\n{content}\n"
                total_code_len += len(content)

            except Exception:
                pass

        # Step 2: Requirement Analysis
        code_prompt = f"""
You are an expert Computer Science instructor reviewing a student's assignment submission.

### Assignment Description
{assignment_desc if assignment_desc else "No assignment description provided."}

### Instructor Solution (Reference)
{solution_content if solution_content else "No instructor solution provided."}

### Student Source Code
{code_content}

### Instructions
Analyze whether the student has fulfilled the assignment requirements:

1. **Completeness**: Did the student complete all required tasks, sections, or questions specified in the assignment?
2. **Correctness**: Does the implementation appear to solve the stated problem correctly?
3. **Approach**: How does the student's approach compare to the expected solution or instructor reference (if provided)?
4. **Critical Issues**: Identify any fundamental errors that would prevent the solution from working as intended.

Focus on WHAT was required and WHETHER it was done, not on code style or minor quality issues.
Do NOT assign a grade. Provide a factual assessment of requirement fulfillment.
"""
        with open(log_path, "a") as log_file:
            log_file.write("--- Step 2: Code Analysis Prompt ---\n")
            log_file.write(code_prompt + "\n\n")

        try:
            code_analysis = self.client.generate_text(
                prompt=code_prompt,
                model=self.config.reviewer_model,
                provider=self.config.reviewer_provider,
                system_prompt="You are an expert teaching assistant focused on evaluating requirement fulfillment, not grading."
            )
            
            with open(log_path, "a") as log_file:
                log_file.write("--- Step 2: Code Analysis Response ---\n")
                log_file.write(code_analysis + "\n\n")

        except Exception as e:
            code_analysis = f"Error analyzing code: {e}"
            with open(log_path, "a") as log_file:
                log_file.write(f"--- Step 2: Code Analysis Error ---\n{e}\n\n")

        # Step 2: Final Review with Execution Output
        # Truncate output if necessary, but be generous. If we have 200k context, and 
        # code analysis is small (e.g. 2k tokens), we have lots of room for output.
        # Let's limit output to 100k chars each to be safe.
        max_output_len = 100000
        if len(stdout) > max_output_len:
            stdout = stdout[:max_output_len] + "\n... [Output Truncated] ..."
        if len(stderr) > max_output_len:
            stderr = stderr[:max_output_len] + "\n... [Output Truncated] ..."

        final_prompt = f"""
You are an expert Computer Science instructor. You have previously analyzed whether the student fulfilled the assignment requirements. Now verify the execution results.

### Requirement Analysis
{code_analysis}

### Execution Output
STDOUT:
{stdout}

STDERR:
{stderr}

### Instructions
Provide a final review focused on requirement verification:

1. **Execution Status**: Did the code run successfully, or were there errors? If errors occurred, do they indicate incomplete implementation?
2. **Output Validation**: Does the execution output demonstrate that the requirements were met? For example:
   - Were required visualizations generated?
   - Were expected calculations or predictions produced?
   - Were questions/analysis sections answered?
3. **Completeness Summary**: Provide a clear summary of:
   - What requirements were fully met
   - What requirements were partially met
   - What requirements were not addressed
4. **Key Feedback**: What are the most important things the student should address?

Do NOT focus on minor code quality issues.
Do NOT assign a numerical grade - provide factual assessment only.

Format the output as clear, actionable Markdown.
"""

        with open(log_path, "a") as log_file:
            log_file.write("--- Step 3: Final Review Prompt ---\n")
            log_file.write(final_prompt + "\n\n")

        review = self.client.generate_text(
            prompt=final_prompt,
            model=self.config.reviewer_model,
            provider=self.config.reviewer_provider,
            system_prompt="You are an expert teaching assistant focused on verifying requirement completion, not assigning grades."
        )

        with open(log_path, "a") as log_file:
            log_file.write("--- Step 3: Final Review Response ---\n")
            log_file.write(review + "\n\n")

        return review

    def generate_metareview(self, reviews: List[str]) -> str:
        """
        Generates a summary of all reviews.
        """
        # If reviews are too long, we might need to summarize chunks.
        # For now, let's assume we can fit a summary of reviews.

        combined_reviews = "\n\n".join([f"--- Review {i+1} ---\n{r[:1000]}..." for i, r in enumerate(reviews)]) # Truncate for context

        prompt = f"""
You are the Head Instructor. Here are summaries of the reviews generated for the class submissions.

{combined_reviews}

Please generate a "Meta-Review" for the whole class that:
1. Identifies common errors or misconceptions.
2. Highlights areas where the class performed well.
3. Suggests topics to review in the next lecture.
4. Provides an overall assessment of the cohort's performance.

Format as Markdown.
"""

        metareview = self.client.generate_text(
            prompt=prompt,
            model=self.config.reviewer_model,
            provider=self.config.reviewer_provider,
            system_prompt="You are an educational data analyst."
        )

        return metareview
